initial commit
romantmb/schemer pull request #1
Opened 2019-11-01 14:41 UTC by romantmb

2019-11-05 16:13 UTC, eddycek requested changes
- namespace mas jen`Schemer`, neude lepsi `Romantmb\Schemer`?
- nejvíc se mi nelíbí class `Node`, z té bych udělal abstraktní class a final class by implementoval jen to co potřebuje, zbytečně moc tam přetěžuješ. Něco podobného máš pak i u těch `inputs`... to bych taky trochu zrevidoval
- všeobecně tam chybí return types, něco jsem dal do suggested changes ale u konce jsem to už nedával (hlavně github to nedal :D)
- všechny exceptions dědí od `SchemerException` která dědí od `LogicException`. Imho `InvalidValueException` je spíš `InvalidArgumentException` etc
- S tím composer.lock jsem se sekl, sorry, u balíčku to nese komplikace při instalaci. Až ve finálním projektu který nikam přes composer neinstaluješ by lock měl být. Takže ještě jednou promiň za mystifikaci. Tady jsem pro smazání.




Neměl jsem moc času si celou knihovnu osahat, takže těch architektonických věcí tam bude asi víc,  ale na první kolečko ty připomínky stejně stačí :)

2019-11-05 16:13 UTC, eddycek commented on src/Schemer/Node.php
> +			->mapWithKeys(function(Node $node) {
```suggestion
			->mapWithKeys(static function(Node $node) {
```

2019-11-05 16:13 UTC, eddycek commented on src/Schemer/Options.php
> +class Options extends Node implements NamedNode
```suggestion
final class Options extends Node implements NamedNode
```

2019-11-05 16:13 UTC, eddycek commented on src/Schemer/Options.php
> +	public function containsPrimitives(): bool
nebude lepší?
```suggestion
	public function isContainsPrimitives(): bool
```

2019-11-05 16:13 UTC, eddycek commented on src/Schemer/Options.php
> +					->map(function(ArrayItem $item) { return $item->getKey(); })
```suggestion
					->map(static function(ArrayItem $item) { return $item->getKey(); })
```

2019-11-05 16:13 UTC, eddycek commented on src/Schemer/Options.php
> +			->map(function(Node $item) { return $item->getChildren(); })
```suggestion
			->map(static function(Node $item) { return $item->getChildren(); })
```

2019-11-05 16:13 UTC, eddycek commented on src/Schemer/Options.php
> +			->filter(function(Property $property) {
```suggestion
			->filter(static function(Property $property) {
```

2019-11-05 16:13 UTC, eddycek commented on src/Schemer/Options.php
> +			->mapWithKeys(function(Property $property) {
```suggestion
			->mapWithKeys(static function(Property $property) {
```

2019-11-05 16:13 UTC, eddycek commented on src/Schemer/Options.php
> +			->mapWithKeys(function(Property $property) {
dál ve funkci jsou asi další dvě

2019-11-05 16:13 UTC, eddycek commented on src/Schemer/Options.php
> +			list($definition, $value) = explode('=', $definition);
btw dá se to zapsat jako
```suggestion
			[$definition, $value] = explode('=', $definition);
```

2019-11-05 16:13 UTC, eddycek commented on src/Schemer/Options.php
> +		if ($this->containsPrimitives() && $value !== null) {
```suggestion
		if ($value !== null && $this->containsPrimitives() ) {
```

2019-11-05 16:13 UTC, eddycek commented on src/Schemer/Options.php
> +		if (!in_array(get_class($item), [ Node::class, ArrayItem::class ])) {
```suggestion
		if (!in_array(get_class($item), [Node::class, ArrayItem::class], true)) {
```

2019-11-05 16:13 UTC, eddycek commented on src/Schemer/Options.php
> +		} elseif ($uniqueKeyCount > 1) {
zbytečný `elseif`

2019-11-05 16:13 UTC, eddycek commented on src/Schemer/Options.php
> +		} elseif ($item instanceof ArrayItem) {
proč elseif?

2019-11-05 16:13 UTC, eddycek commented on src/Schemer/Options.php
> +		} else {
proč else?

2019-11-05 16:13 UTC, eddycek commented on src/Schemer/Property.php
> +class Property extends Node implements NamedNodeWithValue
```suggestion
final class Property extends Node implements NamedNodeWithValue
```

2019-11-05 16:13 UTC, eddycek commented on src/Schemer/Property.php
> +	public function isBag()
```suggestion
	public function isBag(): bool
```

2019-11-05 16:13 UTC, eddycek commented on src/Schemer/Property.php
> +			throw new InvalidNodeException(sprintf("Conditional %s for value %s already defined.", $node instanceof Group ? 'sibling' : 'siblings', self::export($value)));
a `self::export()` nikde nevidím... to je chyba ne?

2019-11-05 16:13 UTC, eddycek commented on src/Schemer/Property.php
> +	public function toArray()
```suggestion
	public function toArray(): array
```

2019-11-05 16:13 UTC, eddycek commented on src/Schemer/ScalarProvider.php
> +class ScalarProvider implements ValueProvider
```suggestion
final class ScalarProvider implements ValueProvider
```

2019-11-05 16:13 UTC, eddycek commented on src/Schemer/Scheme.php
> +		if (sizeof($content) > 1 || sizeof($content) === 1 && $content[0] instanceof NamedNode) {
proč `sizeof`? to je jen alias pro `count` ne?

2019-11-05 16:13 UTC, eddycek commented on src/Schemer/StaticArrayProvider.php
> +	private $values = [];
není potřeba, stačí
```suggestion
	private $values;
```

2019-11-05 16:13 UTC, eddycek commented on src/Schemer/StaticArrayProvider.php
> +				sprintf(" for property '%s'", $this->getProperty()->getName()),
`getProperty()` může vracet null

2019-11-05 16:13 UTC, eddycek commented on src/Schemer/StaticArrayProvider.php
> +			return $value === 'true' ? true : false;
```suggestion
			return $value === 'true';
```

2019-11-05 16:13 UTC, eddycek commented on src/Schemer/Support/Strings.php
> +					strtr($str, $sep, ' ')
zas ten alias :)
```suggestion
					str_replace($str, $sep, ' ')
```

2019-11-05 16:13 UTC, eddycek commented on LICENCE
> +Attribution-ShareAlike 4.0 International
Nebude lepší MIT?

2019-11-05 16:13 UTC, eddycek commented on src/Schemer/UserValueProvider.php
> +	 * @return mixed
```suggestion
	 * @return void
```

2019-11-05 16:13 UTC, eddycek commented on src/Schemer/UserValueProvider.php
> +					sprintf("'%s'", $this->getProperty()->getPath())
`$this->getProperty()` může být null ne?

2019-11-05 16:13 UTC, eddycek commented on src/Schemer/UserValueProvider.php
> +	public function getHumanValue()
Tohle někde používáš? To asi není třeba ne?

2019-11-05 16:13 UTC, eddycek commented on src/Schemer/Validators/Input.php
> +	function getKey();
```suggestion
	function getKey(): ?string;
```

2019-11-05 16:13 UTC, eddycek commented on src/Schemer/Validators/Inputs/BasicInput.php
> +class BasicInput implements Input
```suggestion
abstract class BasicInput implements Input
```
a ostatní nastavit na final?

2019-11-05 16:13 UTC, eddycek commented on src/Schemer/Helpers.php
> +namespace Schemer;
bych klidně dal do namespace `Support`, kdyz uz ji tam mas

2019-11-05 16:33 UTC, eddycek reviewed
Další várka CR

2019-11-05 16:33 UTC, eddycek commented on src/Schemer/Extensions/FormInputSpecification.php
> +			$invalid = is_object($valueProvider) ? ('instance of ' . get_class($valueProvider)) : gettype($valueProvider);
sprintf?

2019-11-05 16:33 UTC, eddycek commented on src/Schemer/Extensions/FormInputSpecification.php
> +			} catch (Exception $e) {
catch nad Exception? To nevím co se tam ve skutečnosti může vyhazovat?

2019-11-05 16:33 UTC, eddycek commented on src/Schemer/Extensions/FormInputSpecification.php
> +	public function setFormControl(object $control = null)
Co je object?

2019-11-05 16:33 UTC, eddycek commented on src/Schemer/Extensions/FormsForSchemer.php
> +	protected $fetchedInputSpecs = [
property máš protected ale nikde od class nedědíš, co to?

2019-11-05 16:33 UTC, eddycek commented on src/Schemer/Extensions/FormsForSchemer.php
> +		foreach ($this->fetch()->all() as $spec) {
tohle nejde iterovat přes collection aby jsi tam nemel ten foreach?

2019-11-05 16:33 UTC, eddycek commented on src/Schemer/Extensions/FormsForSchemer.php
> +			} catch (InvalidValueException | SchemerException $e) {
V tom stávajícím setupu, kdy všechno dědí od `SchemerException` asi není potřeba `InvalidValueException `

2019-11-05 16:33 UTC, eddycek commented on src/Schemer/Extensions/Transformers/InputNameToSchemePathTransformer.php
> +		throw new StaticClassException(sprintf('Methods in %s are for static call only.', self::class));
Zajímavé, docela dobrý nápad jako hint pro usera 👍 
klidně bych udělal abstraktní `StaticClass` a nechal bych to dědit, DRY

2019-11-05 16:33 UTC, eddycek commented on src/Schemer/Group.php
> +		throw new BadMethodCallException('Group members must be defined in constructor.');
Tohle se mi hodně nelíbí, `Node::add()` bych dal do traity a přidal jen v `Options` a `Property`. Navíc `Node` by měla být abstraktní class, co myslíš?

2019-11-05 16:33 UTC, eddycek commented on src/Schemer/Group.php
> +	public function toArray()
tohle to samé, `Arrayable` by měla implementovat jen ta class která to podporuje. Kvli tomu jsou tyhle "able", viz Interface Segregation Principle

2019-11-05 16:33 UTC, eddycek commented on src/Schemer/Group.php
> +	public function toJson($options = 0)
to samé, `Jsonable` implementuje koncová class která to fakt potřebuje

2019-11-06 08:18 UTC, romantmb commented on src/Schemer/Extensions/FormInputSpecification.php
> +			} catch (Exception $e) {
Košer implementace ValueProvider by měla vyhodit InvalidValueException, pokud nemůže být hodnota null. Changed.

2019-11-06 08:21 UTC, romantmb commented on src/Schemer/Extensions/FormInputSpecification.php
> +	public function setFormControl(object $control = null)
Libovolný form control, z libovolného frameworku. Víc než že to musí být object o něm nevím. Je to jen set-in/get-out pro usnadnění práce nad formuláři.

2019-11-06 08:26 UTC, romantmb commented on src/Schemer/Extensions/FormsForSchemer.php
> +	protected $fetchedInputSpecs = [
Přišlo mi na začátku fajn nechat tu třídu extendable. Ale je fakt, že když tam přibyly custom mappery a validátory, už to tolik smysl nedává. Dám jí final.

2019-11-06 08:32 UTC, romantmb commented on src/Schemer/Extensions/FormsForSchemer.php
> +		foreach ($this->fetch()->all() as $spec) {
Done.

2019-11-06 08:32 UTC, romantmb commented on src/Schemer/Extensions/FormsForSchemer.php
> +			} catch (InvalidValueException | SchemerException $e) {
Done.

2019-11-06 08:39 UTC, romantmb commented on src/Schemer/Extensions/Transformers/InputNameToSchemePathTransformer.php
> +		throw new StaticClassException(sprintf('Methods in %s are for static call only.', self::class));
Done.

2019-11-06 08:41 UTC, romantmb commented on src/Schemer/Helpers.php
> +namespace Schemer;
Done.

2019-11-06 08:59 UTC, romantmb commented on src/Schemer/Group.php
> +		throw new BadMethodCallException('Group members must be defined in constructor.');
Node nemůže být abstract, protože třeba celé schéma je `Node`. Ale asi by nebylo marné udělat class `Bag` a helpery `add()` apod. strčit do traity. Ještě promyslím.

2019-11-06 09:02 UTC, romantmb commented on src/Schemer/Options.php
> +	public function containsPrimitives(): bool
To by muselo být `doesContainPrimitives()`, proto jsem šel tím zjednodušeným stylem pojmenování z Laravelu.

2019-11-06 09:06 UTC, romantmb commented on src/Schemer/Options.php
> +		} elseif ($uniqueKeyCount > 1) {
Fixed.

2019-11-06 09:06 UTC, romantmb commented on src/Schemer/Options.php
> +		} else {
Fixed.

2019-11-06 09:07 UTC, romantmb commented on src/Schemer/Options.php
> +		} elseif ($item instanceof ArrayItem) {
Fixed.

2019-11-06 09:31 UTC, romantmb commented on src/Schemer/Property.php
> +			throw new InvalidNodeException(sprintf("Conditional %s for value %s already defined.", $node instanceof Group ? 'sibling' : 'siblings', self::export($value)));
Fixed.

2019-11-06 09:36 UTC, romantmb commented on src/Schemer/Scheme.php
> +		if (sizeof($content) > 1 || sizeof($content) === 1 && $content[0] instanceof NamedNode) {
Fixed.

2019-11-06 09:38 UTC, romantmb commented on src/Schemer/StaticArrayProvider.php
> +	private $values = [];
Musí být defaultně `[]`, kvůli `public function getValues(): array`.

2019-11-06 09:41 UTC, romantmb commented on src/Schemer/StaticArrayProvider.php
> +				sprintf(" for property '%s'", $this->getProperty()->getName()),
Fixed.

2019-11-06 09:41 UTC, romantmb commented on src/Schemer/StaticArrayProvider.php
> +			return $value === 'true' ? true : false;
Fixed.

2019-11-06 09:46 UTC, romantmb commented on src/Schemer/Support/Strings.php
> +					strtr($str, $sep, ' ')
`strtr()` není alias, ale tady byla vyloženě blbě použitá. Dík :-)

2019-11-06 09:50 UTC, romantmb commented on src/Schemer/UserValueProvider.php
> +					sprintf("'%s'", $this->getProperty()->getPath())
Fixed.

2019-11-06 09:53 UTC, romantmb commented on src/Schemer/UserValueProvider.php
> +	public function getHumanValue()
Používám ve třídách, které dědí od `UserValueProvider`. Asi by to bylo čistší přes interface,

2019-11-06 12:14 UTC, eddycek commented on src/Schemer/UserValueProvider.php
> +	public function getHumanValue()
jop, přes interface a z tohohle uděláš abstraktní funkci aby si to každý naimplementoval sám

2019-11-08 12:43 UTC, romantmb commented on src/Schemer/Node.php
> +			->mapWithKeys(function(Node $node) {
Done.

2019-11-08 12:44 UTC, romantmb commented on src/Schemer/Options.php
> +class Options extends Node implements NamedNode
Done.

2019-11-08 12:45 UTC, romantmb commented on src/Schemer/Options.php
> +					->map(function(ArrayItem $item) { return $item->getKey(); })
Done.

2019-11-08 12:45 UTC, romantmb commented on src/Schemer/Options.php
> +			->map(function(Node $item) { return $item->getChildren(); })
Done.

2019-11-08 12:45 UTC, romantmb commented on src/Schemer/Options.php
> +			->filter(function(Property $property) {
Done.

2019-11-08 12:45 UTC, romantmb commented on src/Schemer/Options.php
> +			->mapWithKeys(function(Property $property) {
Done.

2019-11-08 12:46 UTC, romantmb commented on src/Schemer/Options.php
> +			list($definition, $value) = explode('=', $definition);
Done

2019-11-08 12:46 UTC, romantmb commented on src/Schemer/Options.php
> +		if ($this->containsPrimitives() && $value !== null) {
Done

2019-11-08 12:47 UTC, romantmb commented on src/Schemer/Options.php
> +		if (!in_array(get_class($item), [ Node::class, ArrayItem::class ])) {
Done

2019-11-08 12:48 UTC, romantmb commented on src/Schemer/Property.php
> +class Property extends Node implements NamedNodeWithValue
Done

2019-11-08 12:48 UTC, romantmb commented on src/Schemer/Property.php
> +	public function isBag()
Fixed

2019-11-08 12:50 UTC, romantmb commented on src/Schemer/ScalarProvider.php
> +class ScalarProvider implements ValueProvider
Done

2019-11-08 12:58 UTC, romantmb commented on src/Schemer/Validators/Input.php
> +	function getKey();
Fixed

2019-11-08 12:59 UTC, romantmb commented on src/Schemer/Validators/Inputs/BasicInput.php
> +class BasicInput implements Input
Done

2019-11-14 18:44 UTC, eddycek commented on src/Schemer/UserValueProvider.php
> +	public function getHumanValue()
@romantmb tohle není vyřešené ne?

2019-11-14 18:47 UTC, eddycek commented on src/Schemer/Group.php
> +		throw new BadMethodCallException('Group members must be defined in constructor.');
Přesně, když ne abstract tak společnou logiku extrahovat do traity. Klidně můžeme nechat na jindy, založil bych na to issue.

2019-11-14 18:48 UTC, eddycek commented on src/Schemer/Group.php
> +	public function toArray()
@romantmb tohle jsi neřešil?

2019-11-14 18:48 UTC, eddycek commented on src/Schemer/Group.php
> +	public function toJson($options = 0)
@romantmb ?

2019-11-15 12:20 UTC, eddycek approved these changes
lgtm, jen naházej ty neudělané věci do issues

2019-11-15 13:00 UTC, merged